spring:
  application:
    name: govisaviya
  profiles:
    active: development


server:
  servlet:
    context-path: /govisaviya
  port: ${PORT:8080}
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
  structured:
    format:
      console: logstash
      file: logstash

