package com.megaminds.govisaviya.dto.response;

import lombok.Data;

import java.util.List;

/**
 * Top-level response DTO for the Pl@ntNet disease identification API.
 *
 * @param <T> Type of the result (typically a JsonNode)
 */
@Data
public class IdentifiedDisease<T> {

    /** S3 URLs of all images uploaded with this request. */
    private List<String> imageUrls;

    /** Full disease identification result from Pl@ntNet. */
    private T result;

    /**
     * Actionable treatment / solution generated by Gemini 2.5 Flash
     * based on the top disease name returned by Pl@ntNet.
     */
    private String solution;

}
